name: CI/CD

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - run: |
        pip install -r requirements.txt
        pytest
        python app.py

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - run: echo "Deploying..."
